export const UNLOCK_LOCKER_TOPIC = "lockers/cmd/";
export const LOCKER_UNLOCKED_EVENT = "LOCKER_UNLOCKED";
export const DEVICE_ONLINE_EVENT = "DEVICE_BACK_ONLINE";
export const DEVICE_OFFLINE_EVENT = "DEVICE_OFFLINE";
export const DEVICE_REGISTERED_EVENT = "DEVICE_REGISTERED";
export const DEVICE_VALIDATION_FAILED_EVENT = "DEVICE_VALIDATION_FAILED";
export const DEVICE_REGISTER_FAILED_EVENT = "DEVICE_REGISTER_FAILED";
